spring:
  application:
    name: smartlogi-sdms

  datasource:
    url: jdbc:postgresql://localhost:5432/smartlogi1_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Configuration JWT (Sortie du bloc spring pour plus de clarté)
jwt:
  secret: "duainIbvm6qS9wZvHcHgswRdH0QiBhbpirG37iS1AHcv00rPWBkss7jz0zQ8EGq0tWcCgBoaVcn+jnoh4UIRew=="
  expiration:
    ms: 86400000